#!/usr/bin/env python3
"""
check-word-frequency.py — flags word-bank entries that are barely real English.

Diagnostic only. Never edits the banks. Writes docs/wordbank-frequency.md.

Requirements (not in package.json — Python tooling, like make-brand-assets.py):
    pip install wordfreq

Why this exists
---------------
`audit-wordbank.js` measures the *shape* of a tier — endings, composition, rhyme
concentration. It cannot tell whether a word is one anybody uses. That gap let entries
like `officialize`, `territorialization` and `groundlessness` sit in tier 3: strings a
suffix rule can build but no writer will ever pick up. A prompt like that does not just
fail to inspire, it costs a writer one of the twenty or so words they see in a session.

The measure is Zipf frequency from the `wordfreq` package — a log scale over a mixed
corpus (books, subtitles, web, news). Roughly:

    7  the, of            5  common noun
    4  everyday word      3  known but not frequent
    2  rare               <1.5  effectively not in use

The floors below are judgement calls, and deliberately conservative. Rap vocabulary
skews away from general English — a battle rapper genuinely reaches for `sycophant`
(2.2) or `proboscis` (2.4) — so this is a list to review, not a cut list to run. What it
catches unambiguously is the bottom: a word at 0.0 appears in the corpus essentially
never, and that is a data-quality fault rather than a matter of taste.
"""

import json
from pathlib import Path

from wordfreq import zipf_frequency

ROOT = Path(__file__).resolve().parent.parent
TIERS = {t: json.loads((ROOT / f"src/data/tier-{t}.json").read_text()) for t in (1, 2, 3)}

# Not in use at all vs. merely uncommon. Only the first is unambiguous.
DEAD = 1.5
THIN = 2.3


def main():
    lines = ["# Word frequency check", "",
             "Generated by `python3 scripts/check-word-frequency.py`. Diagnostic only.", "",
             "Zipf frequency over a mixed English corpus: 4 is an everyday word, 3 is known",
             "but not frequent, below 1.5 is effectively not in use.", "",
             "**This is a list to review, not a cut list.** Rap vocabulary skews away from",
             "general English, so an uncommon word is not automatically a bad prompt —",
             "`sycophant` sits at 2.2 and earns its place. The bottom of the range is the",
             "unambiguous part: a word at 0.0 appears in the corpus essentially never.", ""]

    summary = []
    for tier, bank in TIERS.items():
        scored = sorted(((w, zipf_frequency(w, "en")) for w in bank), key=lambda x: x[1])
        dead = [(w, z) for w, z in scored if z < DEAD]
        thin = [(w, z) for w, z in scored if DEAD <= z < THIN]
        summary.append((tier, len(bank), len(dead), len(thin)))

        lines += [f"## Tier {tier} — {len(bank)} words", ""]
        lines += [f"- **{len(dead)}** below {DEAD} (effectively not in use)",
                  f"- **{len(thin)}** between {DEAD} and {THIN} (rare; review by ear)", ""]
        if dead:
            lines += ["### Not in use", "",
                      "These are the clear faults — strings a suffix rule can build that no",
                      "writer will pick up. Removing them costs no vocabulary.", "",
                      " · ".join(f"`{w}` {z:.1f}" for w, z in dead), ""]
        if thin:
            lines += ["### Rare — review by ear", "",
                      " · ".join(f"`{w}` {z:.1f}" for w, z in thin[:80]), ""]
            if len(thin) > 80:
                lines += [f"…and {len(thin) - 80} more.", ""]

    (ROOT / "docs").mkdir(exist_ok=True)
    (ROOT / "docs/wordbank-frequency.md").write_text("\n".join(lines) + "\n")

    print("Word frequency check\n")
    for tier, total, dead, thin in summary:
        print(f"  tier {tier}: {total} words | {dead} not in use (<{DEAD}) | {thin} rare (<{THIN})")
    print("\nWrote docs/wordbank-frequency.md")


if __name__ == "__main__":
    main()
